repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      language: system
      entry: black
      types: [python]
      language_version: python3.6
